apiVersion: v1
kind: Service
metadata:
  name: serverloader
  labels:
    app: serverloader
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: serverloader