apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: serverloader
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serverloader
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 80Mi
        maxAllowed:
          cpu: 2
          memory: 1000Mi
        controlledResources: ["cpu", "memory"]