apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: serverloader
  namespace: serverloader
spec:
  scaleTargetRef:
    name: serverloader
  minReplicaCount: 2
  maxReplicaCount: 30
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress:  http://keda-prom-auth.kube-system.svc.cluster.local
        metricName: http_requests_received_total
        threshold: '100'
        query: sum(rate(http_requests_received_total{ app="serverloader", code="200", endpoint="/workout"}[1m]))