apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: serverloader
  namespace: serverloader
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serverloader
  updatePolicy:
    updateMode: "Recreate"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 250m
          memory: 100Mi
        maxAllowed:
          cpu: 1000m
          memory: 300Mi
        controlledResources: ["cpu", "memory"]